### ISSUE TITLE
Should we use an example where camel case is the expected case? field name, operation name, parameter name.

### ISSUE THREAD

**Issue by externl** [icerpc/icerpc-docs#124]
Should we use an example where camel case is the expected case? field name, operation name, parameter name.

For types, the expected case is pascal case so this situation should never arise.

_Originally posted by @bernardnormier in https://github.com/icerpc/icerpc-docs/pull/100#discussion_r1256298427_

**Comment by ReeceHumphreys** [comment]
This page has been removed from the docs
