### ISSUE TITLE
Should we Document Compact IDs in the Class Language Guide

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#332]
Currently, we have no documentation of compact IDs even existing.

This will change when I document them grammatically in the language reference,
but to keep the reference focused on the grammar, I was planning to just add a link:
"for more information about compact IDs, click here"
However there is nothing to link to.

Should we add at least a small section in Class Language Guide for compact IDs?
While not common, if we're going to talk about Slicing and graph preservation, I think compact IDs at least deserves a mention.

**Comment by bernardnormier** [comment]
Yes, we should mention compact IDs (compact type IDs?) on the class page in the Language Guide.

Note that they apply only to classes and not exceptions.

**Comment by InsertCreativityHere** [comment]
Alright, I'll open a small PR to add a section for them, so I can link it in the language reference.
I suppose "Compact Type ID" is the more correct term.
