### ISSUE TITLE
Fix link to API reference

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/icerpc-docs#341]
We want API reference to link to: https://docs.icerpc.dev/api/csharp/index.html

See https://github.com/icerpc/icerpc-csharp/issues/3651

**Comment by ReeceHumphreys** [comment]
This issue has been fixed by https://github.com/icerpc/icerpc-docs/commit/9eee1fd4ff1ac94d58b29f1d2d41e0431f33906c.
