### ISSUE TITLE
Do we Ignore Positive Feedback?

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#350]
I tried leaving both positive and negative feedback on the docs, but I only see an email about the negative feedback.
Is this expected behavior, or just email being email?

I agree that negative feedback is more important to focus on, but I think it's kind of strange to just completely throw away the positive feedback. It could still be possibly valuable to let us know when we're going in the right direction with something.

**Comment by ReeceHumphreys** [comment]
Seems to be working as expected. The only notable thing was the email was sent to my junk email folder which happens to lots of mail for me as my mailbox is a bit overzealous with the filtering.

<img width="968" alt="Screenshot 2023-09-20 at 9 16 50 AM" src="https://github.com/icerpc/icerpc-docs/assets/14209515/0e871861-ced2-4047-a036-a707932df351">
