### ISSUE TITLE
Weird Whitespace Between Side-Nav and Footer

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#353]
![image](https://github.com/icerpc/icerpc-docs/assets/25963603/65ac50d7-7fc6-45c0-93e0-385512b72050)
The bottom of the side-nav just ends, despite there being plenty of usable space left for it to extend into.

Triggering the "Was the page helpful?" exaggerates the effect, but it still happens even without it, until you scroll all the way to bottom.

**Comment by externl** [comment]
This was intentional to allow the footer to be displayed on short pages. I agree it looks weird so I'll remove it.
