### ISSUE TITLE
Some "Edit this Page" Links are Broken

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#357]
Navigating to: https://docs.icerpc.dev/slice2, and clicking "Edit this Page" tries to open:
"https://github.com/icerpc/icerpc-docs/tree/main/pages/slice.md" But this page doesn't exist.

The issue is that it's an overview page, so the file isn't named "Slice", it's named "index".
This probably happens on the other overview pages as well.

**Comment by ReeceHumphreys** [comment]
This is fixed in PR #356 I believe.

**Comment by InsertCreativityHere** [comment]
My local server is running off the "Checkpoint 2" commit, and it still seems broken.

**Comment by InsertCreativityHere** [comment]
I just saw the new commit. It seems fixed now.
Should probably wait to close this until after your PR is merged though.

**Comment by ReeceHumphreys** [comment]
> I just saw the new commit. It seems fixed now!
> Should probably wait to close this until after your PR is merged though.

Yeh I had the fix locally just did not have it committed. When the PR is merged it will automatically close this issue.
