### ISSUE TITLE
Reading Times are not Computed Correctly for Slice1-only Pages

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#373]
Both of the following pages say they only take 1 minute to read:
- https://docs.icerpc.dev/slice1/language-guide/class-types
- https://docs.icerpc.dev/slice1/language-guide/exception

Despite the pages being substantially longer than the struct page: https://docs.icerpc.dev/slice1/language-guide/struct-types
which has an estimated reading time of 2 minutes.

I suspect these pages just aren't being picked up at all.

**Comment by ReeceHumphreys** [comment]
I suspect it is only looking at the content for Slice2 mode which for those pages is just once sentence which would explain the one min reading time.
