### ISSUE TITLE
Add Documentation for `Result`

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#414]
Now that we've added full support for `Result<S, F>` to the parser, code-gen, and C# mapping...
we need to add documentation for it:
- We need a new section under "Dictionary" titled "Result", which explains results.
- A new section in the encoding reference, even if it just says "We encode it like <this>. Go read the enum encoding"

**Comment by bernardnormier** [comment]
Again, see the csharp-0.3-dev branch.
